### ISSUE TITLE
death bug.

### ISSUE THREAD

**Issue by shaswata56** [shaswata56/Taos-Adventure#4]
**Shoytan er loge laigga morle screen soira jay**

**To Reproduce**
1. Go to 'Newgame'
2. Get died by 'shoytan'
**(if you want to see more)**
3. Click 'Backspace'
4. Go to Step 1.

**Expected behavior**
Game should load again without any overflow.

**Screenshots**

**Desktop**
 - OS: [Manjaro Linux 4.19.2]

**Comment by KhanShaheb34** [comment]
Ekhon Valomoto Moira Jay... Innalillahi Wa Inna Ilaihi Rajiun... :'(
